# Build Settings
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Zhiqing Xu Personal Page]
description: [Chemical Engineering PhD Candidate | Protein Design & Bioinformatics | NLP & Speech Recognition | University of Toronto]
show_downloads: false


